## Here we define two functions which will allow a matrix inverse to be calculated
## and stored, such that subsequent calls to calculate the inverse will load the
## result from previous computation instead. This is a slightly modified version
## of the similar script taking means provided in the exercise text.

## This function establishes an environment in which the matrix inverse to its 
## input matrix x can be stored using setinverse(). It can be extracted by getinverse(). 
## Only one matrix can be stored at once, and changing the source matrix wipes
## the previous stored inverse.

makeCacheMatrix <- function(x = matrix()) {
        inverse <- NULL
        set <- function(y) {
                x <<- y
                inverse <<- NULL
        }
        get <- function() x
        setinverse <- function(I) inverse <<- I
        getinverse <- function() inverse
        list(set = set, get = get,
             setinverse = setinverse,
             getinverse = getinverse)
}

## This function takes as input the list of functions generated by 
## makeCacheMatrix and returns the matrix inverse, using the stored value if it
## has been previously set.

cacheSolve <- function(x, ...) {
        I <- x$getinverse()
        if(!is.null(I)) {
                message("getting cached data")
                return(I)
        }
        data <- x$get()
        I <- solve(data, ...)
        x$setinverse(I)
        I
}
